name: Upload PDF to Google Drive
on:
  push:
    branches: [ main ]
jobs:
  build-examples:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install dependencies
          run: apk update && apk add texmf-dist texlive texmf-dist-latexextra nodejs

        - name: Set PDF Filename
          id: set_filename
          run: echo "::set-output name=pdf_filename::utc_article_$(date +'%d-%m-%Y')"

        - name: Build examples
          run: cp -r utc-*/* examples && cd examples && pdflatex -interaction=nonstopmode -halt-on-error -jobname="${{ steps.set_filename.outputs.pdf_filename }}" utc-*.tex

        - name: Upload PDF TO Google Drive
          uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.2.2
          with:
            target: examples/${{ steps.set_filename.outputs.pdf_filename }}.pdf
            credentials: ${{ secrets.GDRIVE_TOKEN }}
            parent_folder_id: ${{ secrets.GDRIVE_FOLDER }}
            override: true
