name: Build and upload the examples PDF to GitHub Artifacts and Pages

on:
  push

jobs:
  build-examples:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/utc-latex-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build examples files
        env:
          EXAMPLES: "utc-article.tex utc-report.tex utc-beamer.tex"
        run: |
          mv examples/*.tex .
          mv examples/img .
          for file in $EXAMPLES; do
            pdflatex -interaction=nonstopmode -halt-on-error "$file"
            pdflatex -interaction=nonstopmode -halt-on-error "$file"
          done

      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: utc-latex
          path: |
            utc-article.pdf
            utc-report.pdf
            utc-beamer.pdf

      - name: Create public directory with full index
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p public
          mv utc-article.pdf utc-report.pdf utc-beamer.pdf public/
          cat <<EOF > public/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <title>UTC LaTeX Examples</title>
          </head>
          <body>
            <h1>UTC LaTeX PDF Examples</h1>
            <ul>
              <li><a href="utc-article.pdf">utc-article.pdf</a> — Article template</li>
              <li><a href="utc-report.pdf">utc-report.pdf</a> — Report template</li>
              <li><a href="utc-beamer.pdf">utc-beamer.pdf</a> — Beamer template</li>
            </ul>
            <p>See the full source code on <a href="https://github.com/${{ github.repository }}">GitHub</a>.</p>
          </body>
          </html>
          EOF


      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          allow_empty_commit: true
          force_orphan: true
          enable_jekyll: true
