name: Build and upload the examples PDF to GitHub Artifacts at each commit
on:
  push
jobs:
  build-examples:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install dependencies
          run: apk update && apk add texmf-dist texlive texmf-dist-latexextra \
               texmf-dist-langfrench-2024 \ 
               nodejs

        - name: Build examples
          run: cp -r utc-*/* examples && cd examples && pdflatex -interaction=nonstopmode -halt-on-error utc-*.tex

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: utc-latex
            path: examples/utc-article.pdf
