name: Build and upload the examples PDF to GitHub Artifacts at each commit
on:
  push
jobs:
  build-examples:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install dependencies
          run: pacman -Sy --noconfirm texlive texlive-basic texlive-latex texlive-latexextra texlive-lang 

        - name: Set environements variables
          run: export TEXINPUTS=".:../utc-article:../utc-beamer:../utc-common:../utc-report:"

        - name: Build "utc-article"
          run: cd examples && pdflatex -interaction=nonstopmode -halt-on-error utc-article.tex

        - name: Upload "utc-article"
          uses: actions/upload-artifact@v4
          with:
            name: utc-latex
            path: examples/utc-article.pdf
