name: Build and upload the examples PDF to GitHub Artifacts and Pages

on:
  push

jobs:
  build-examples:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/utc-latex-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build examples files
        env:
          EXAMPLES: "utc-article.tex utc-report.tex utc-beamer.tex"
        run: |
          mv examples/*.tex .
          mv examples/img .
          for file in $EXAMPLES; do
            pdflatex -interaction=nonstopmode -halt-on-error "$file"
            pdflatex -interaction=nonstopmode -halt-on-error "$file"
          done

      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: utc-latex
          path: |
            utc-article.pdf
            utc-report.pdf
            utc-beamer.pdf

      - name: Create public directory with full index
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p public
          mv utc-article.pdf utc-report.pdf utc-beamer.pdf public/
          cp utc-common/utc_su_logo.png public/
          cat <<EOF > public/index.html
          <!DOCTYPE html>
          <html lang="fr">
          <head>
            <meta charset="UTF-8">
            <title>UTC LaTeX Examples</title>
            <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
            <style>
              body {
                font-family: 'Roboto', sans-serif;
                background-color: #fdfdfd;
                color: #222;
                max-width: 800px;
                margin: 40px auto;
                padding: 20px;
                line-height: 1.6;
              }

              header {
                display: flex;
                align-items: center;
                gap: 16px;
                border-bottom: 2px solid #ddd;
                padding-bottom: 10px;
                margin-bottom: 30px;
              }

              header img {
                height: 64px;
                width: auto;
              }

              h1 {
                font-size: 2em;
                margin: 0;
              }

              ul {
                list-style: none;
                padding: 0;
              }

              li {
                margin: 12px 0;
              }

              a {
                color: #0060aa;
                text-decoration: none;
              }

              a:hover {
                text-decoration: underline;
              }

              footer {
                margin-top: 40px;
                font-size: 0.9em;
                color: #555;
              }
            </style>
          </head>
          <body>
            <header>
              <img src="utc_su_logo.png" alt="UTC logo">
              <h1>UTC LaTeX — PDF Examples</h1>
            </header>

            <ul>
              <li><a href="utc-article.pdf">utc-article.pdf</a> — Template article</li>
              <li><a href="utc-report.pdf">utc-report.pdf</a> — Template rapport</li>
              <li><a href="utc-beamer.pdf">utc-beamer.pdf</a> — Template présentation Beamer</li>
            </ul>

            <footer>
              Voir le code source sur <a href="https://github.com/${{ github.repository }}">GitHub</a>.
            </footer>
          </body>
          </html>
          EOF


      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          allow_empty_commit: true
          force_orphan: true
          enable_jekyll: true
