name: Build and upload the examples PDF to GitHub Artifacts at each commit

on:
  push

jobs:
  build-examples:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/utc-latex-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build examples
        env:
          TEXINPUTS: ".:../utc-article:../utc-beamer:../utc-common:../utc-report:"
          EXAMPLES: "utc-article.tex utc-report.tex utc-beamer.tex"
        run: |
          cd examples
          for file in $EXAMPLES; do
            pdflatex -interaction=nonstopmode -halt-on-error "$file"
          done

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: utc-latex
          path: |
            examples/utc-article.pdf
            examples/utc-report.pdf
            examples/utc-beamer.pdf
